### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by pgporada** [on2itsecurity/etcd-operator#42]
I've searched everywhere for someone who has managed to keep this project up to date. You're a life saver. I've tried improbable-eng, bitnami-etcd, running a single etcd which I didn't want to do, and upgrading the code myself.

**Comment by pgporada** [comment]
I've updated the old stable/etcd-exporter helm chart to now work with this fork. I've got it running successfully in one of my clusters. https://github.com/pgporada/etcd-operator-helm-chart

**Comment by nberlee** [comment]
Thats absolutely great! Helmcharts are a great addition for adoption, and I was contemplating creating it myself I am happy that you picked that from my plate.
